import type { EntitlementResult, IntakeAnswers, Benefit, Rule, RuleOp } from '../lib/types'
import { getTriageMode } from './questions'

// Import the compiled benefits dataset
// This is generated by `npm run data:build` from the YAML source files
import benefitsData from '../../../data/dist/benefits.json'

const benefits = benefitsData as Benefit[]

// ── Fact derivation ──

// Accommodation Supplement zones (simplified)
const ZONE_1_REGIONS = ['Auckland', 'Wellington']
const ZONE_2_REGIONS = ['Canterbury / Christchurch']

function getAccomZone(region: string): number {
  if (ZONE_1_REGIONS.includes(region)) return 1
  if (ZONE_2_REGIONS.includes(region)) return 2
  return 3
}

function getAccomMaxWeekly(zone: number): number {
  if (zone === 1) return 305
  if (zone === 2) return 250
  return 175
}

// Build a flat facts object from raw intake answers
export function buildFacts(answers: IntakeAnswers): Record<string, unknown> {
  const income = Number(answers['income.amount'] ?? 0)
  const partnerIncome = Number(answers['personal.partner_income'] ?? 0)
  const hours = Number(answers['income.hours'] ?? 0)
  const housingCost = Number(answers['housing.cost'] ?? 0)
  const region = String(answers['housing.region'] ?? 'Other')
  const accomZone = getAccomZone(region)
  const accomMax = getAccomMaxWeekly(accomZone)
  const housingCostRatio = income > 0 ? housingCost / income : (housingCost > 0 ? 1 : 0)
  const age = Number(answers['personal.age'] ?? 0)
  const childAges = (answers['children.ages'] ?? []) as string[]
  const healthCostTypes = (answers['health.cost_types'] ?? []) as string[]

  // Education mapping
  const isStudent = answers['education.studying'] === 'Yes'
  const studyLevelMap: Record<string, string> = {
    'Certificate / Diploma': 'certificate_diploma',
    "Bachelor's degree": 'bachelors',
    'Postgraduate (Honours)': 'postgrad_honours',
    'Masters': 'masters',
    'PhD / Doctorate': 'phd'
  }
  const studyLevel = studyLevelMap[String(answers['education.level'] ?? '')] ?? ''
  const studyLoad = String(answers['education.load'] ?? '').toLowerCase() || ''
  const studyPapers = Number(answers['education.papers'] ?? 0)

  // Residency mapping
  const residencyMap: Record<string, string> = {
    'NZ Citizen': 'citizen',
    'Permanent Resident': 'permanent_resident',
    'Resident Visa': 'resident_visa',
    'Refugee / Protected Person': 'refugee',
    'Other visa': 'other'
  }

  // Relationship mapping
  const relationship = String(answers['personal.relationship'] ?? 'Single')
  const hasPartner = ['In a relationship / de facto', 'Married / civil union'].includes(relationship)
  const isSoleParent = !hasPartner && answers['children.dependent'] === 'Yes'

  // Asset mapping
  const assetAnswer = String(answers['income.assets'] ?? 'Unsure')
  const assetsUnder8100 = assetAnswer === 'Under $8,100'
  const assetsUnder16200 = assetAnswer === 'Under $8,100' || assetAnswer === '$8,100 – $16,200'

  return {
    // Personal
    age,
    residency_status: residencyMap[String(answers['personal.residency'] ?? '')] ?? 'other',
    years_in_nz: Number(answers['personal.years_in_nz'] ?? 0),
    has_partner: hasPartner,
    is_sole_parent: isSoleParent,
    partner_income: partnerIncome,

    // Housing
    housing_type: String(answers['housing.type'] ?? '').toLowerCase().replace(/ /g, '_'),
    has_housing: ['Renting', 'Boarding', 'Mortgage'].includes(String(answers['housing.type'] ?? '')),
    housing_cost: housingCost,
    housing_cost_ratio: housingCostRatio,
    accom_zone: accomZone,
    accom_max: accomMax,
    region,
    is_social_housing: answers['housing.social_housing'] === 'Yes',
    has_rent_arrears: answers['housing.arrears'] === 'Yes',
    needs_to_move: answers['housing.need_to_move'] === 'Yes',
    at_risk_of_eviction: answers['housing.arrears'] === 'Yes',
    is_homeless: false, // derived from no housing + emergency
    needs_bond_assistance: answers['housing.need_to_move'] === 'Yes',
    has_accommodation_costs: housingCost > 0,

    // Income
    is_employed: answers['income.employed'] === 'Yes',
    weekly_income: income,
    hours_worked: hours,
    on_benefit: answers['income.benefit'] === 'Yes',
    on_main_benefit: answers['income.benefit'] === 'Yes',
    benefit_type: String(answers['income.benefit_type'] ?? ''),
    annual_income: income * 52,
    low_income: income < 800,
    very_low_income: income < 450,
    household_income: income + partnerIncome,
    assets_under_8100: assetsUnder8100,
    assets_under_16200: assetsUnder16200,
    asset_range: assetAnswer,

    // Health
    has_condition: answers['health.condition'] === 'Yes',
    condition_duration: String(answers['health.duration'] ?? ''),
    has_ongoing_disability_costs: answers['health.costs'] === 'Yes',
    has_health_costs: answers['health.costs'] === 'Yes',
    has_health_related_costs: answers['health.costs'] === 'Yes',
    has_extra_clothing_costs: false, // not directly asked, could be derived
    has_extra_power_costs: healthCostTypes.includes('Extra power / heating'),
    needs_home_modifications: healthCostTypes.includes('Home modifications needed'),
    hours_able: String(answers['health.hours_able'] ?? ''),
    unable_to_work: answers['health.hours_able'] === 'Unable to work',
    work_capacity_under_15: ['Unable to work', 'Less than 15 hrs'].includes(String(answers['health.hours_able'] ?? '')),
    in_residential_care: answers['health.residential_care'] === 'Yes',
    has_chronic_condition: answers['health.duration'] === 'More than 2 years' || answers['health.duration'] === 'Permanent / lifelong',

    // Children
    has_children: answers['children.dependent'] === 'Yes',
    child_count: Number(answers['children.count'] ?? 0),
    child_ages: childAges,
    has_child_under_3: childAges.some(a => a === 'Under 1 year' || a === '1 – 2 years'),
    youngest_child_under_14: childAges.some(a => ['Under 1 year', '1 – 2 years', '3 – 4 years', '5 – 13 years'].includes(a)),
    child_in_ece: answers['children.childcare'] === 'Yes',
    child_in_childcare: answers['children.childcare'] === 'Yes',
    has_child_with_disability: answers['children.disability'] === 'Yes',
    child_disability: answers['children.disability'] === 'Yes',
    is_caring_for_unsupported_child: answers['children.caring_for_other'] === 'Yes',
    is_caring_for_orphan: answers['children.caring_for_other'] === 'Yes', // simplified

    // Employment
    is_seeking_work: answers['employment.seeking_work'] === 'Yes',
    unemployment_duration: String(answers['employment.unemployment_duration'] ?? ''),
    interested_in_training: answers['employment.training_interest'] === 'Yes',
    in_approved_training: answers['employment.training_interest'] === 'Yes', // simplified
    interested_in_apprenticeship: answers['employment.training_interest'] === 'Yes',
    is_seasonal_worker: answers['employment.seasonal'] === 'Yes',
    in_off_season: answers['employment.seasonal'] === 'Yes', // simplified
    starting_self_employment: answers['employment.self_employed'] === 'Yes',
    has_barriers_to_employment: answers['employment.unemployment_duration'] === 'More than 12 months',
    starting_employment: false, // not directly asked
    work_ready: answers['employment.unemployment_duration'] === 'Less than 4 weeks',

    // Education
    is_student: isStudent,
    study_level: studyLevel,
    study_load: studyLoad,
    is_postgrad: ['masters', 'phd'].includes(studyLevel),
    is_postgrad_above_honours: ['masters', 'phd'].includes(studyLevel),
    study_papers: studyPapers,
    study_hours_equivalent: studyPapers * 10, // NZ: 1 paper ≈ 10hrs/wk
    in_study_break: false, // placeholder — not asked in intake

    // Situation
    in_emergency: answers['situation.emergency'] === 'Yes',
    experiencing_family_violence: answers['situation.family_violence'] === 'Yes',
    recently_released: answers['situation.recently_released'] === 'Yes',
    is_refugee: answers['situation.refugee'] === 'Yes',
    recently_arrived: answers['situation.refugee'] === 'Yes', // simplified
    is_full_time_carer: answers['situation.carer'] === 'Yes',
    affected_by_civil_defence_emergency: false, // rare, not asked

    // Derived compound facts
    essential_costs_exceed_income: (housingCostRatio > 0.3) || (answers['health.costs'] === 'Yes'),
    has_essential_need: answers['situation.emergency'] === 'Yes' || income < 450,
    has_urgent_need: answers['situation.emergency'] === 'Yes',
    in_hardship: income < 450 && !answers['income.benefit'],
    has_special_circumstances: answers['situation.emergency'] === 'Yes',
    has_housing_need: answers['housing.arrears'] === 'Yes' || answers['housing.need_to_move'] === 'Yes',
    needs_to_relocate: answers['housing.need_to_move'] === 'Yes',
    relocating_for_employment: answers['housing.need_to_move'] === 'Yes' && answers['employment.seeking_work'] === 'Yes',
    has_tenancy_costs: answers['housing.need_to_move'] === 'Yes',
    on_social_housing_wait_list: false, // not asked directly
    is_working_sufficient_hours: hasPartner
      ? (hours + Math.round(partnerIncome / 23.15)) >= 30
      : hours >= 20,
    partner_estimated_hours: hasPartner ? Math.round(partnerIncome / 23.15) : 0,
    couple_combined_income: hasPartner ? income + partnerIncome : income,
    couple_income_high: hasPartner && (income + partnerIncome) > 250,
    partner_income_above_abatement: hasPartner && partnerIncome > 160,
    not_employed: answers['income.employed'] !== 'Yes',
    not_in_education: !isStudent,
    needs_establishment_support: answers['situation.family_violence'] === 'Yes' || (relationship === 'Separated' && answers['housing.need_to_move'] === 'Yes'),
    needs_long_term_care: answers['health.residential_care'] === 'Yes' && (answers['health.duration'] === 'More than 2 years' || answers['health.duration'] === 'Permanent / lifelong'),
    needs_community_support: answers['health.residential_care'] === 'Yes',
    has_property: false, // not asked
    has_funeral_costs: false, // not a standard intake question
    has_newborn: childAges.includes('Under 1 year'),
    not_receiving_paid_parental_leave: true, // assumed
    has_school_costs: childAges.some(a => ['5 – 13 years', '14 – 17 years'].includes(a)),
    family_income: income + partnerIncome,

    // Triage
    triage_mode: getTriageMode(answers),
    in_crisis_mode: getTriageMode(answers) === 'crisis',
    in_sanctions_mode: getTriageMode(answers) === 'sanctions',
    in_appeal_mode: getTriageMode(answers) === 'appeal',
    crisis_needs_food: Array.isArray(answers['triage.crisis_needs']) && (answers['triage.crisis_needs'] as string[]).includes('Food'),
    crisis_needs_rent: Array.isArray(answers['triage.crisis_needs']) && (answers['triage.crisis_needs'] as string[]).includes('Rent or housing costs'),
    crisis_needs_power: Array.isArray(answers['triage.crisis_needs']) && (answers['triage.crisis_needs'] as string[]).includes('Power or heating'),
    crisis_needs_medical: Array.isArray(answers['triage.crisis_needs']) && (answers['triage.crisis_needs'] as string[]).includes('Medical costs'),
    benefit_was_reduced: answers['triage.sanction_type'] === 'Reduced',
    benefit_was_stopped: answers['triage.sanction_type'] === 'Stopped completely',
    sanction_not_notified: answers['triage.sanction_notified'] === 'No',
    sanction_no_written_reason: answers['triage.sanction_written'] === 'No' || answers['triage.sanction_written'] === 'No reason given',
    appeal_target: String(answers['triage.appeal_benefit'] ?? ''),
    // Crisis/sanctions imply emergency + urgent need
    ...(getTriageMode(answers) === 'crisis' || getTriageMode(answers) === 'sanctions' ? {
      in_emergency: true,
      has_urgent_need: true,
      has_essential_need: true,
      has_special_circumstances: true,
    } : {}),
  }
}

// ── Rule evaluation ──

function evaluateRule(rule: Rule, facts: Record<string, unknown>): { pass: boolean; evaluated: boolean } {
  const factValue = facts[rule.fact]

  // If the fact doesn't exist in our facts object, we can't evaluate
  if (factValue === undefined || factValue === null) {
    // exists/not_exists can be evaluated even for undefined
    if (rule.op === 'not_exists') return { pass: true, evaluated: true }
    if (rule.op === 'exists') return { pass: false, evaluated: true }
    return { pass: false, evaluated: false }
  }

  switch (rule.op) {
    case 'eq':
      return { pass: factValue === rule.value, evaluated: true }
    case 'neq':
      return { pass: factValue !== rule.value, evaluated: true }
    case 'in':
      return { pass: Array.isArray(rule.value) && rule.value.includes(factValue), evaluated: true }
    case 'not_in':
      return { pass: Array.isArray(rule.value) && !rule.value.includes(factValue), evaluated: true }
    case 'gt':
      return { pass: Number(factValue) > Number(rule.value), evaluated: true }
    case 'gte':
      return { pass: Number(factValue) >= Number(rule.value), evaluated: true }
    case 'lt':
      return { pass: Number(factValue) < Number(rule.value), evaluated: true }
    case 'lte':
      return { pass: Number(factValue) <= Number(rule.value), evaluated: true }
    case 'exists':
      return { pass: true, evaluated: true }  // already checked above
    case 'not_exists':
      return { pass: false, evaluated: true }  // already checked above
    default:
      return { pass: false, evaluated: false }
  }
}

function getDisplayAmount(benefit: Benefit): string | undefined {
  if (!benefit.rates) return undefined
  if (benefit.rates.max_weekly) return benefit.rates.max_weekly
  if (benefit.rates.max_fortnightly) return benefit.rates.max_fortnightly
  if (benefit.rates.fixed_amount) return benefit.rates.fixed_amount
  if (benefit.rates.max_annual) return benefit.rates.max_annual
  if (benefit.rates.max_one_off) return benefit.rates.max_one_off
  if (benefit.rates.description) return benefit.rates.description
  return undefined
}

function generateAction(benefit: Benefit, status: string): string {
  const name = benefit.name

  if (status === 'ENTITLED') {
    return `Request a written ${name} assessment at your appointment. If already receiving, confirm the amount is correct.`
  }
  if (status === 'POSSIBLE') {
    const docs = benefit.friction?.documentation_required
    const docHint = docs && docs.length > 0
      ? ` Bring: ${docs.slice(0, 2).join(', ')}.`
      : ''
    return `Ask the case manager to assess your eligibility for ${name}. There is no downside to requesting this.${docHint}`
  }
  return `You may be eligible for ${name} but more information is needed. Raise this at your appointment to confirm.`
}

// Evaluate a single benefit against the facts
function evaluateBenefit(benefit: Benefit, facts: Record<string, unknown>): EntitlementResult | null {
  const rules = benefit.eligibility.rules ?? []

  // No rules = can't auto-evaluate, skip
  if (rules.length === 0) return null

  let passed = 0
  let evaluated = 0
  let failed = 0

  for (const rule of rules) {
    const result = evaluateRule(rule, facts)
    if (result.evaluated) {
      evaluated++
      if (result.pass) {
        passed++
      } else {
        failed++
        // If a critical rule fails, exclude benefit entirely
        if (rule.critical) return null
      }
    }
  }

  // If no rules could be evaluated, skip
  if (evaluated === 0) return null

  // Determine status and confidence
  const total = rules.length
  const passRatio = passed / total
  const evaluatedRatio = evaluated / total

  let status: 'ENTITLED' | 'POSSIBLE' | 'INSUFFICIENT_INFORMATION'
  let confidence: number

  // Filter: if any rule explicitly failed, need a high pass ratio to still surface
  if (failed > 0 && passRatio < 0.5) {
    return null
  }

  // Filter: if we have very few rules (1-2) and any failed, skip
  if (total <= 2 && failed > 0) {
    return null
  }

  if (passed === total) {
    // All rules pass
    status = 'ENTITLED'
    confidence = Math.min(95, 70 + Math.round(passRatio * 25))
  } else if (failed === 0 && evaluatedRatio < 0.5) {
    // Not enough data to evaluate most rules — only show if we have some signal
    if (passed < 2) return null
    status = 'INSUFFICIENT_INFORMATION'
    confidence = Math.round(30 + passRatio * 20)
  } else if (passRatio >= 0.7) {
    // Most rules pass
    status = 'POSSIBLE'
    confidence = Math.round(50 + passRatio * 30)
  } else if (passRatio >= 0.5 && failed <= 1) {
    // Majority pass with at most 1 fail — worth mentioning
    status = 'POSSIBLE'
    confidence = Math.round(40 + passRatio * 25)
  } else {
    // Not enough signal — don't surface
    return null
  }

  // Check age constraints
  const age = Number(facts.age ?? 0)
  if (benefit.eligibility.min_age != null && age > 0 && age < benefit.eligibility.min_age) {
    return null
  }
  if (benefit.eligibility.max_age != null && age > 0 && age > benefit.eligibility.max_age) {
    return null
  }

  // Check residency
  const residency = String(facts.residency_status ?? '')
  if (benefit.eligibility.residency && benefit.eligibility.residency.length > 0 && residency && residency !== 'other') {
    if (!benefit.eligibility.residency.includes(residency)) {
      return null
    }
  }

  // Check requires_benefit
  if (benefit.eligibility.requires_benefit === true && facts.on_benefit !== true) {
    // Downgrade to possible if not on benefit but might qualify
    if (status === 'ENTITLED') {
      status = 'POSSIBLE'
      confidence = Math.max(40, confidence - 20)
    }
  }

  return {
    entitlement_type: benefit.id.toUpperCase().replace(/-/g, '_'),
    name: benefit.name,
    category: benefit.category,
    frequency: benefit.frequency,
    status,
    confidence,
    legal_basis: benefit.legal_basis ?? '',
    weekly_amount: getDisplayAmount(benefit),
    action: generateAction(benefit, status),
    conditions: benefit.eligibility.conditions ?? [],
    documentation_required: benefit.friction?.documentation_required ?? [],
    deflection_patterns: benefit.friction?.deflection_patterns ?? [],
    typical_processing: benefit.friction?.typical_processing,
    known_issues: benefit.friction?.known_issues ?? [],
    description: benefit.description,
    advocacy: benefit.advocacy,
  }
}

// ── Main entry point ──

const CRISIS_CATEGORIES = new Set(['hardship', 'housing'])

export async function evaluateEntitlements(answers: IntakeAnswers): Promise<EntitlementResult[]> {
  const facts = buildFacts(answers)
  const triageMode = getTriageMode(answers)
  const results: EntitlementResult[] = []

  for (const benefit of benefits) {
    const result = evaluateBenefit(benefit, facts)
    if (result) {
      // Crisis/sanctions mode: only surface hardship + housing categories
      if ((triageMode === 'crisis' || triageMode === 'sanctions') && !CRISIS_CATEGORIES.has(result.category)) {
        continue
      }
      results.push(result)
    }
  }

  // Sort: ENTITLED first, then POSSIBLE, then INSUFFICIENT by confidence
  const order = { ENTITLED: 0, POSSIBLE: 1, INSUFFICIENT_INFORMATION: 2 }
  results.sort((a, b) => {
    const statusDiff = (order[a.status] ?? 2) - (order[b.status] ?? 2)
    if (statusDiff !== 0) return statusDiff
    return b.confidence - a.confidence
  })

  // Appeal mode: put the declined benefit first
  if (triageMode === 'appeal') {
    const appealTarget = String(answers['triage.appeal_benefit'] ?? '')
    if (appealTarget) {
      const targetKey = appealTarget.toUpperCase().replace(/ /g, '_')
      results.sort((a, b) => {
        const aMatch = a.entitlement_type === targetKey || a.name === appealTarget ? -1 : 0
        const bMatch = b.entitlement_type === targetKey || b.name === appealTarget ? -1 : 0
        return aMatch - bMatch
      })
    }
  }

  // Crisis/sanctions: sort hardship before housing
  if (triageMode === 'crisis' || triageMode === 'sanctions') {
    results.sort((a, b) => {
      if (a.category === 'hardship' && b.category !== 'hardship') return -1
      if (a.category !== 'hardship' && b.category === 'hardship') return 1
      return 0
    })
  }

  return results
}
