import fs from 'fs'
import path from 'path'
import yaml from 'js-yaml'
import Ajv2020 from 'ajv/dist/2020.js'

const ROOT = path.resolve(import.meta.dirname)
const BENEFITS_DIR = path.join(ROOT, 'benefits')
const RATES_DIR = path.join(ROOT, 'rates')
const SCHEMA_PATH = path.join(ROOT, 'schema', 'benefit.schema.json')
const DIST_DIR = path.join(ROOT, 'dist')

// Ensure dist exists
fs.mkdirSync(DIST_DIR, { recursive: true })

// Load and compile schema
const schema = JSON.parse(fs.readFileSync(SCHEMA_PATH, 'utf-8'))
const ajv = new Ajv2020({ allErrors: true, strict: false })
const validate = ajv.compile(schema)

// Recursively find all YAML files under a directory
function findYamlFiles(dir: string): string[] {
  const results: string[] = []
  if (!fs.existsSync(dir)) return results

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      results.push(...findYamlFiles(full))
    } else if (entry.name.endsWith('.yaml') || entry.name.endsWith('.yml')) {
      results.push(full)
    }
  }
  return results
}

// Load all benefit YAML files
const benefitFiles = findYamlFiles(BENEFITS_DIR)
console.log(`Found ${benefitFiles.length} benefit files`)

const benefits: unknown[] = []
let errors = 0

for (const file of benefitFiles) {
  const relPath = path.relative(ROOT, file)
  try {
    const content = yaml.load(fs.readFileSync(file, 'utf-8'))
    const valid = validate(content)
    if (!valid) {
      console.error(`\n❌ ${relPath}:`)
      for (const err of validate.errors ?? []) {
        console.error(`   ${err.instancePath || '/'} — ${err.message}`)
      }
      errors++
    } else {
      benefits.push(content)
    }
  } catch (e: any) {
    console.error(`\n❌ ${relPath}: ${e.message}`)
    errors++
  }
}

// Load rate tables
const rateFiles = findYamlFiles(RATES_DIR)
const rates: Record<string, unknown> = {}

for (const file of rateFiles) {
  const name = path.basename(file, path.extname(file))
  try {
    rates[name] = yaml.load(fs.readFileSync(file, 'utf-8'))
  } catch (e: any) {
    console.error(`\n❌ rates/${path.basename(file)}: ${e.message}`)
    errors++
  }
}

if (errors > 0) {
  console.error(`\n🛑 ${errors} validation error(s). Build failed.`)
  process.exit(1)
}

// Write outputs
fs.writeFileSync(
  path.join(DIST_DIR, 'benefits.json'),
  JSON.stringify(benefits, null, 2)
)
console.log(`✓ dist/benefits.json (${benefits.length} benefits)`)

fs.writeFileSync(
  path.join(DIST_DIR, 'rates.json'),
  JSON.stringify(rates, null, 2)
)
console.log(`✓ dist/rates.json (${Object.keys(rates).length} rate tables)`)

// Generate TypeScript types
const typesContent = `// Auto-generated by data/build.ts — do not edit manually

export type RuleOp = 'eq' | 'neq' | 'in' | 'not_in' | 'gt' | 'gte' | 'lt' | 'lte' | 'exists' | 'not_exists'

export type Rule = {
  fact: string
  op: RuleOp
  value?: unknown
}

export type BenefitCategory = 'main' | 'supplement' | 'hardship' | 'housing' | 'family' | 'employment' | 'health' | 'residential' | 'other'
export type PaymentFrequency = 'weekly' | 'fortnightly' | 'one-off' | 'annual' | 'automatic' | 'as-needed'

export type RateTable = {
  name: string
  by?: string[]
  rows: Record<string, unknown>[]
}

export type Benefit = {
  id: string
  name: string
  category: BenefitCategory
  frequency: PaymentFrequency
  taxable: boolean
  legal_basis?: string
  source_url?: string
  description: string

  eligibility: {
    min_age?: number | null
    max_age?: number | null
    residency?: string[]
    residence_years?: number | null
    requires_benefit?: boolean
    benefit_types?: string[]
    requires_application?: boolean
    rules?: Rule[]
    conditions?: string[]
  }

  rates?: {
    effective?: string
    fixed_amount?: string
    max_weekly?: string
    max_fortnightly?: string
    max_annual?: string
    max_one_off?: string
    description?: string
    tables?: RateTable[]
  }

  income_test?: {
    applies?: boolean
    description?: string
    thresholds?: Record<string, unknown>[]
  }

  asset_test?: {
    applies?: boolean
    single?: number
    couple_or_sole_parent?: number
    description?: string
  }

  friction?: {
    documentation_required?: string[]
    typical_processing?: string
    known_issues?: string[]
    deflection_patterns?: string[]
  }
}
`

fs.writeFileSync(path.join(DIST_DIR, 'types.ts'), typesContent)
console.log('✓ dist/types.ts')

console.log(`\n✅ Build complete. ${benefits.length} benefits, ${Object.keys(rates).length} rate tables.`)
